version: '3.8'
services:
  app-test:
    build:
      context: .
      dockerfile: Dockerfile.test
    container_name: app-test
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '5'
    working_dir: /usr/src/app
    command: yarn test
    volumes:
      - ./coverage:/usr/src/app/coverage
    environment:
      NODE_ENV: test
