version: '3.8'
services:
  app-development:
    build:
      context: .
      dockerfile: Dockerfile.development
    ports:
      - ${PORT}:${PORT}
    container_name: app-development
    restart: always
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '5'
    volumes:
      - .:/usr/src/app
      - node_modules:/usr/src/app/node_modules
    working_dir: /usr/src/app
    environment:
      NODE_ENV: development
    command: yarn dev
volumes:
  node_modules:
