name: Test
on:
  pull_request:
    branches: [main]
jobs:
  test:
    runs-on: ubuntu-20.04
    timeout-minutes: 10
    strategy:
      matrix:
        node-version: [16.x]
        python-version: [3.8]
    steps:
      - uses: actions/checkout@v2

      - name: Environment variables setup
        run: |
          cd $GITHUB_WORKSPACE
          echo "$SECRETS" > ./.github/workflows/scripts/env.json
          node ./.github/workflows/scripts/generate-test-env.js
        env:
          SECRETS: ${{ toJson(secrets) }}

      - name: Build test compose
        run: make test
